services:
  - type: web
    name: tujulishane-hub-backend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    rootDir: backend
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: GEOCODING_API_KEY
        sync: false
    healthCheckPath: /api/projects/thematic-areas

  - type: web
    name: tujulishane-hub-frontend
    runtime: static
    buildCommand: ""
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN